version: "2"
services: 
    # app
    app:
        container_name: evaluos-app
        build: 
            context: ../
            dockerfile: Docker/Dockerfile
        ports: 
            - "5000:5000"
    # Database
    database:
        image: mysql:5.6
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - "3308:3306"

    #Start phpmyadmin instance connected to db
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            PMA_USER: homestead
            PMA_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
volumes:
    dbdata: