"""empty message

Revision ID: 95d54feb2c70
Revises: cd94e68cc666
Create Date: 2020-09-07 19:20:06.683558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = '95d54feb2c70'
down_revision = 'cd94e68cc666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_recovery_token',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('user_id', UUIDType(binary=False), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_recovery_token')
    # ### end Alembic commands ###
